from pyspark.sql.types import StructType, StructField, StringType, TimestampType
silver_schema = StructType([
  StructField("unique_key",                     StringType(),    False),
  StructField("created_date",                   TimestampType(), True),
  StructField("closed_date",                    TimestampType(), True),
  StructField("due_date",                       TimestampType(), True),
  StructField("resolution_action_updated_date", TimestampType(), True),
  StructField("agency",                         StringType(),    True),
  StructField("agency_name",                    StringType(),    True),
  StructField("complaint_type",                 StringType(),    True),
  StructField("descriptor",                     StringType(),    True),
  StructField("location_type",                  StringType(),    True),
  StructField("status",                         StringType(),    True),
  StructField("resolution_description",         StringType(),    True),
  StructField("incident_zip",                   StringType(),    True),
  StructField("city",                           StringType(),    True),
  StructField("borough",                        StringType(),    True),
  StructField("community_board",                StringType(),    True),
  StructField("council_district",               IntegerType(),   True),
  StructField("police_precinct",                StringType(),    True),
  StructField("open_data_channel_type",         StringType(),    True),
  StructField("address_type",                   StringType(),    True),
  StructField("latitude",                       DoubleType(),    True),
  StructField("longitude",                      DoubleType(),    True),
  StructField("x_coordinate",                   DoubleType(),    True),
  StructField("y_coordinate",                   DoubleType(),    True),
  StructField("record_version",                 TimestampType(), True),
  StructField("batch_id",                       StringType(),    True),
  StructField("source_file",                    StringType(),    True),
  StructField("load_timestamp",                 TimestampType(), False),
])

print(len(silver_schema.fields), "silver columns")
