from pyspark.sql.types import StructType, StructField, StringType, TimestampType, IntegerType, DoubleType

silver_schema = StructType([
  StructField("unique_key", StringType(), False),
  StructField("created_date", TimestampType()),
  StructField("closed_date", TimestampType()),
  StructField("name", StringType()),
  StructField("agency", StringType()),
  StructField("agency_name", StringType()),
  StructField("complaint_type", StringType()),
  StructField("descriptor", StringType()),
  StructField("descriptor_2", StringType()),
  StructField("location_type", StringType()),
  StructField("incident_zip", StringType()),
  StructField("incident_address", StringType()),
  StructField("street_name", StringType()),
  StructField("cross_street_1", StringType()),
  StructField("cross_street_2", StringType()),
  StructField("intersection_street_1", StringType()),
  StructField("intersection_street_2", StringType()),
  StructField("address_type", StringType()),
  StructField("city", StringType()),
  StructField("landmark", StringType()),
  StructField("facility_type", StringType()),
  StructField("status", StringType()),
  StructField("due_date", TimestampType()),
  StructField("resolution_description", StringType()),
  StructField("resolution_action_updated_date", TimestampType()),
  StructField("community_board", StringType()),
  StructField("council_district", IntegerType()),
  StructField("fbicr_code", StringType()),
  StructField("police_precinct", StringType()),
  StructField("latitude", DoubleType()),
  StructField("bbl", StringType()),
  StructField("borough", StringType()),
  StructField("location", StringType()),
  StructField("x_coordinate", DoubleType()),
  StructField("y_coordinate", DoubleType()),
  StructField("longitude", DoubleType()),
  StructField("open_data_channel_type", StringType()),
  StructField("park_facility_name", StringType()),
  StructField("park_borough", StringType()),
  StructField("vehicle_type", StringType()),
  StructField("taxi_company_borough", StringType()),
  StructField("taxi_pick_up_location", StringType()),
  StructField("bridge_highway_name", StringType()),
  StructField("bridge_highway_direction", StringType()),
  StructField("road_ramp", StringType()),
  StructField("bridge_highway_segment", StringType()),
  StructField("load_timestamp", TimestampType()),
  StructField("source_file", StringType()),
  StructField("batch_id", StringType())
])
