name: NYC 311 API Ingestion

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"

jobs:
  api_ingestion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requests
        run: pip install requests

      - name: Run NYC 311 API ingestion
        working-directory: ${{ github.workspace }}
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          ls -la
          python api_call.py --load incremental --days 2 --max-rows 50000
